### ISSUE TITLE
0.17.0-play26 and 0.17.0-play27 are not published on maven central

### ISSUE THREAD

**Issue by kailuowang** [ReactiveMongo/ReactiveMongo-Play-Json#102]
https://search.maven.org/search?q=g:org.reactivemongo%20AND%20a:reactivemongo-play-json_2.11&core=gav

The only one that got published is 0.17.0-play25

**Comment by cchantep** [comment]
Play 2.6+ are not compatible with Scala 2.11 (indicated in your query): https://search.maven.org/search?q=g:org.reactivemongo%20AND%20a:reactivemongo-play-json_2.12&core=gav
