### ISSUE TITLE
problems using JSONAggregationFramework

### ISSUE THREAD

**Issue by mizerlou** [ReactiveMongo/Reactivemongo-Play-Json#11]
the following code:
`collection.aggregate(
        Match(Json.obj("name" -> "xxx")),
        List(GroupField("userId")("total" -> SumField("count")))
      )
        .map(_.firstBatch)
        .map(_.headOption match {
          case Some(x) => (x \ "total").as[Int]
          case None    => -51
        })
`

craps out with with an exception like this:
`exception[[RuntimeException: (,List(ValidationError(List(CommandError[code=59, errmsg=no such command: 'allowDiskUse', bad cmd: '{ allowDiskUse: false, explain: false, aggregate: "diagnosis", pipeline: [ { $match: { userId: "guest@example.com" } }, { $group: { _id: "$userId", total: { $sum: "$itemsAnalyzed" } } } ], bypassDocumentValidation: false }', doc: {"ok":0,"errmsg":"no such command: 'allowDiskUse', bad cmd: '{ allowDiskUse: false, explain: false, aggregate: \"diagnosis\", pipeline: [ { $match: { userId: \"guest@example.com\" } }, { $group: { _id: \"$userId\", total: { $sum: \"$itemsAnalyzed\" } } } ], bypassDocumentValidation: false }'","code":59}]),WrappedArray())))]]`

the problem appears to be that mongo expects the json fields in a particular order for certain operations.  this isn't a problem with BSON because (apparently) BSON preserves order.  since play/json does not preserve field order, "aggregate" isn't the first field and mongo can't parse the command.

**Comment by pshadow** [comment]
Is there a solution for this? I've got the same error while using a simple query.

**Comment by mizerlou** [comment]
@pshadow check PR#12 https://github.com/ReactiveMongo/Reactivemongo-Play-Json/pull/12/files
