### ISSUE TITLE
Backward compatibility broken in 0.12.4

### ISSUE THREAD

**Issue by 1gnition** [ReactiveMongo/ReactiveMongo-Play-Json#68]
Hi,

This is a major issue because it **breaks all code that deals with catching unique key exceptions**.

The problem can be traced back to this commit: https://github.com/ReactiveMongo/ReactiveMongo-Play-Json/commit/a9c8e5e0fefc1c279c2dd26281652c66d531e91e

### Library Dependencies
`"org.reactivemongo" %% "play2-reactivemongo" % "0.12.5-play25"`
`"com.typesafe.play" % "sbt-plugin" % "2.5.4"`
### Expected Behavior

When using `findAndUpdate`, duplicate key error causes a `JsResultException`, and all code that uses:
```scala
recover {
  case WriteResult.Code(11000) =>
    println("Match the code 11000")
}
```
won't work (see section _Error handling_ from http://reactivemongo.org/releases/0.12/documentation/tutorial/write-documents.html). The `case WriteResult.Code(11000)` will never match.

### Actual Behavior

Should work as I described in the previous section. 

### Reproducible Test Case

First, run the following code with play2-reactivemongo 0.12.0. Then, upgrade to 0.12.5-play25 and run again. The `case` won't execute because it's not longer `WriteResult`.

```scala
import play.api.libs.concurrent.Execution.Implicits._
import play.api.libs.json.Json
import reactivemongo.api.MongoDriver
import reactivemongo.api.commands.WriteResult
import reactivemongo.play.json.ImplicitBSONHandlers._
import reactivemongo.play.json.collection.JSONCollection

import scala.concurrent.Await
import scala.concurrent.duration.Duration

object Main {
  def main(args: Array[String]): Unit = {
    val driver = new MongoDriver()
    val conn = driver.connection(List("localhost:27017"))
    val db = Await.result(conn.database("test"), Duration.Inf)
    val col = db.collection[JSONCollection]("col")

    Await.result(col.insert(Json.obj("a" -> 1)), Duration.Inf)
    
    val f = col.findAndUpdate(
      Json.obj("b" -> 100),
      Json.obj("$setOnInsert" -> Json.obj("a" -> 1)),
      upsert = true
    ) map { _ =>
      println("good")
    } recover {
      case WriteResult.Code(11000) => println("Match the code 11000")
    }
    Await.result(f, Duration.Inf)
  }
}
```

**Comment by cchantep** [comment]
Hi,

The indicated commit isn't related in anyway with `WriteResult` or associated pattern matching.

What's remaining is an issue in the doc (other github repo) the `.recover` must be applied before map to handle orginal result.

**Comment by 1gnition** [comment]
Hi,

Thank you for the response. 

I tried switching the `map` and `recover` and the unique key exception is still not caught in the `case WriteResult.Code(11000) =>` case.

Currently, we deal with 11000 errors on `findAndUpdate` in the following way:

```scala
col.findAndUpdate(
  Json.obj("b" -> 100),
  Json.obj("$setOnInsert" -> Json.obj("a" -> 1)),
  upsert = true
} recover {
  case JsResultException((_, ValidationError(s :: _) :: _) :: _) if s matches ".*code=11000[^\\w\\d].*" =>
    println("Matched case")
}
```

while the `insert` API is much simpler:

```scala
col.insert(Json.obj("a" -> 1)) recover {
  case WriteResult.Code(11000) =>
    println("Matched case")
}
```

So I have two questions:
1. Is the difference in handling 11000 errors between `insert()` and `findAndUpdate()` deliberate or incidental? It's quite unintuitive that the error handling is different between the APIs. It could ease development if they were uniform. I'd be glad to help and contribute if it's necessary
2. If it's deliberate, and not incidental, then what is the canonical way of handling 11000 in the `findAndUpdate` case? Is there a clean solution other than `case JsResultException((_, ValidationError(s :: _) :: _) :: _) if s matches ".*code=11000[^\\w\\d].*" =>`?

**Comment by cchantep** [comment]
The `findAndModify` functions are [not returning `WriteResult` but `FindAndModifyResult`](http://reactivemongo.org/releases/0.12/api/index.html#reactivemongo.api.collections.GenericCollection@findAndUpdate[S,T](selector:S,update:T,fetchNewObject:Boolean,upsert:Boolean,sort:Option[GenericCollection.this.pack.Document],fields:Option[GenericCollection.this.pack.Document])(implicitswriter:GenericCollection.this.pack.Writer[S],implicitwriter:GenericCollection.this.pack.Writer[T],implicitec:scala.concurrent.ExecutionContext):scala.concurrent.Future[GenericCollection.this.BatchCommands.FindAndModifyCommand.FindAndModifyResult]), so it make sense that pattern matching using `WriteResult` utilities doesn't find anything.

**Comment by 1gnition** [comment]
Hi,

So the way I proposed for matching against 11000 error (`case JsResultException((_, ValidationError(s :: _) :: _) :: _) if s matches ".*code=11000[^\\w\\d].*" =>`) is fine or is there a more convenient way to achieve it?

The main problem is that once the reader determines this is an error (i.e. `ok` is not `1`) it [creates a `JsError` with some String](https://github.com/ReactiveMongo/ReactiveMongo-Play-Json/blob/master/src/main/scala/commands.scala#L66-L70), instead of an object, so you have no choice but to search for `11000` inside that string.

**Comment by cchantep** [comment]
It makes no sense. `JsResultException` is only for representing serialization error with the JSON pack, not server failure.

**Comment by cchantep** [comment]
Rather use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question. This tracker is for confirmed issue.
