### ISSUE TITLE
High Object Allocation causing unnecessary garbage collection

### ISSUE THREAD

**Issue by chetankm-cs** [ReactiveMongo/ReactiveMongo-Play-Json#97]
### ReactiveMongo-Play-Json Version (0.11.6, 0.11.11 / etc)
0.12.7-play25

### ReactiveMongo Version (0.11.6, 0.11.11 / etc)
0.12.7

### MongoDB version (2.6, 3.0 / etc)
3.4.4

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)
Linux ip-172-31-27-188 4.4.0-1037-aws #40-Ubuntu SMP Thu Dec 6 11:23:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)
 java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

### Library Dependencies
Playversion 2.5.6

### Expected Behavior
On profiling a read-heavy application, I noticed high number of gc events.
On further profiling using JFR, it showed `BSONFormats.toJson` and `BSONFormats.toJson` create lots of unnecessary `PartialFunction.OrElse` instances. 

Please describe the expected behavior of the issue, starting from the first action.

1. The converters for JSON <-> BSON conversion should be initialized once and reused.

### Actual Behavior

The converters are initialized for every serialization/deserialization operation [here](https://github.com/ReactiveMongo/ReactiveMongo-Play-Json/blob/d9820440988f11266ae4e63075d4e63a5271b432/src/main/scala/package.scala#L651).

<img width="1151" alt="screen shot 2019-03-08 at 10 38 39 pm" src="https://user-images.githubusercontent.com/1472061/54043620-119ef800-41f3-11e9-9632-2fcbf859cbd6.png">

**Comment by cchantep** [comment]
The partial reads/writes are stable Val's declared in (Singleton) objects, so not initialized multiple times.

**Comment by chetankm-cs** [comment]
@cchantep  On every invocation of `BSONFormats.toBSON` from `JSONSerializationPack.scala`, 
we will combine partialReads using `orElse` which will generate around ~17 new [`OrElse`](https://github.com/scala/scala/blob/38cd84d976880eab16af17a44d186bbddcd554f2/src/library/scala/PartialFunction.scala#L80) instances.

**Comment by chetankm-cs** [comment]
@cchantep Thanks for taking the time to fix this issue, however the fix doesn't work as expected. 
Consider this example and the associated output. 

```
def pfGenerator(i: Int): PartialFunction[Int, String] = {
  case `i` => i.toString
}

// stable vals
val p1 = pfGenerator(1)
val p2 = pfGenerator(2)

def readAsBSONValue(i: Int): String = {
  println("Object allocation")
  p1.orElse(p2)
    .lift.apply(i)
    .getOrElse("exception")
}

val defaultRead: Int => String = readAsBSONValue

def toBson(i: Int) : String = defaultRead(i)

println(toBson(1))
println(toBson(2))

// Output
Object allocation 
1
Object allocation
2
```
I am also submitting a pull request which fixes this issue.
